- name: yum-cron
  become: yes
  block:
    - yum:
        name: yum-cron
        state: present
    - template:
        src: yum-cron.conf
        dest: /etc/yum/yum-cron.conf
        owner: root
        group: root
        mode: 0644
      notify: restart yum-cron
    - service:
        name: yum-cron
        state: started
        enabled: true

