- name: Create swapfile so we can run stuff without requiring bigger instance
  become: yes
  block:
    - name: Register swapfile status
      stat: path=/var/swapfile
      register: swapfile

    - name: Write swapfile
      command: |
        dd if=/dev/zero of=/var/swapfile bs=1M count={{ swapfile_size }} creates=/var/swapfile
      when: swapfile.stat.exists == False

    - name: Update perms on swapfile
      file: path=/var/swapfile mode=0600
      when: swapfile.stat.exists == False

    - name: Create swapfile
      command: mkswap /var/swapfile
      when: swapfile.stat.exists == False

    - name: Enable swapfile
      command: swapon -f /var/swapfile
      when: swapfile.stat.exists == False

    - name: Add swapfile to /etc/fstab
      lineinfile: dest=/etc/fstab line="/var/swapfile none swap sw 0 0" state=present

    - name: Configure vm.swappiness
      sysctl:
        name: vm.swappiness
        value: 10
        state: present

    - name: Configure vm.vfs_cache_pressure
      sysctl:
        name: vm.vfs_cache_pressure
        value: 200
        state: present

